### ISSUE TITLE
Databases do not get updated

### ISSUE THREAD

**Issue by nikwen** [runk/node-geolite2#10]
There haven't been any database updates for 11 months. Would it be possible to update them whenever they get released (first Tuesday of each month)?

**Comment by iamstarkov** [comment]
travis supports cron jobs

**Comment by runk** [comment]
Would appreciate if someone sends a pr

**Comment by iamstarkov** [comment]
@runk oof. for that to work, you will need to configure GITHUB_TOKEN in this repo's config on Travis. so cron job, could push updated files back to repo.

**Comment by runk** [comment]
I don't mind setting this up. Guessing some scripting has to happen first?

**Comment by iamstarkov** [comment]
alright

**Comment by runk** [comment]
Should be resolved via https://github.com/runk/node-geolite2/pull/11
