### ISSUE TITLE
npm install fails on Windows

### ISSUE THREAD

**Issue by stephenpoole** [runk/node-geolite2#12]
It appears the package runs a bash script on postinstall, which can't run on Windows.

```
yarn add v1.17.3
warning package.json: License should be a valid SPDX license expression
warning server@1.0.0: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
⠁
⠁
⠁
⠁
error A:\http\htdocs\gamer-dating-app\server\node_modules\geolite2: Command failed.
Exit code: 1
Command: scripts\postinstall
Arguments:
Directory: A:\http\htdocs\server\node_modules\geolite2
```

**Comment by GitSquared** [comment]
#11 added a bash script with implicit dependencies on bash, curl, tar and gunzip (and I may have missed some). As such the 2.0.0 release is not compatible with Windows anymore, or any system that doesn't have these deps.

**Comment by runk** [comment]
Hm.. It's definitely a breaking change, and I'd like this and https://github.com/runk/node-geolite2/issues/13 be addressed. I made it very clear it's a major change, which is indicated in major version bump. Obviously solution for now is to continue using v1.

Let me see how this is resolved in other libraries that do downloads in post-install step.

cc @baleevskiy

**Comment by GitSquared** [comment]
@runk I would suggest doing this with a .js script instead of a shell script. You could offload the cross-platform compatibility problem to a curl-like npm module.

My 2 cents.

**Comment by runk** [comment]
Yeah, might have to do that

**Comment by stephenpoole** [comment]
Node http is cross platform, so any module would do fine. I usually use
request personally. Another good choice is gulp, though that would limit
potential contributors since it's not as popular.

**Comment by runk** [comment]
Downloading is only part of the task, databases come in tar.gz archives

**Comment by stephenpoole** [comment]
Sure, there are packages that handle that for both node and gulp.

**Comment by runk** [comment]
v2.0.1 is out - give it a go

**Comment by GitSquared** [comment]
@runk thanks for the update. I get `ENOENT: No such file or directory /dbs/GeoLite2-Country.mmdb` errors on my CI builds - perhaps you need to add something like `path.join(__dirname,...)`?

**Comment by runk** [comment]
Hm. That's weird. Just installed it locally and confirmed all files resolve well. Can you please narrow down the problem?

Re absolute path - it's already there https://github.com/runk/node-geolite2/blob/master/index.js#L5
