### ISSUE TITLE
Export the download script

### ISSUE THREAD

**Issue by silverwind** [runk/node-geolite2#21]
I think it'd be useful if this module would export its download script. Hypothetical API:

```js
import {download} from 'node-geolite2';
await download({edition, licenseKey, downloadPath});
```

Happy to take a `Buffer` return value too.

**Comment by runk** [comment]
Do you want to craft a PR for that?

**Comment by silverwind** [comment]
Yes, I'm interested.

What's your preference on output? Only download to a path, return a Buffer or maybe both?

I'd like to hand the resulting file to `maxmind` which seems to currently only accept paths, but doing it all in-memory would be useful too I guess.

**Comment by runk** [comment]
🤷‍♂ I'd say returning a buffer is minimum. Don't see reasons why we cannot have boths export methods - via buffer and to path.

**Comment by runk** [comment]
Closing it for now as not active. @silverwind feel free to send a PR if you're still interested in doing it.
