### ISSUE TITLE
Trouble installing on a monorepo

### ISSUE THREAD

**Issue by mehmetnyarar** [runk/node-geolite2#22]
I have a monorepo with the following structure:

```
root
  /packages
    /server
      .env
```

When I try `yarn workspace @app/server add geolite2`, installation throws an error: "License key is not configured."

I also added `.env` to the root directory but no luck.

**Comment by runk** [comment]
Not sure it's a problem of this package. It expects licence key in environment, how you put it in there - separate question. Looks like you're managing env vars via .env files - I'd look into that direction. All this error means is it cannot find the key, that's it.
