### ISSUE TITLE
Add another option to set MAXMIND_LICENSE_KEY

### ISSUE THREAD

**Issue by natanavra** [runk/node-geolite2#23]
There is no easy/simple way to set environment variables when using Google App Engine for example.
Tried npm scripts setting the variable, but it's not being captured/read by the post install / download script of the module

Any ideas how to approach this?

When having control over the environment, e.g. EC2, you can set the environment variable before running `npm install`
There's geolite2-redist repo, but I'm wondering if it can be done with this repo

**Comment by runk** [comment]
AFAIK `geolite2-redist` doesn't require you to provide the key, it rather implies you adhere to the conditions of the original licence from Maxmind

**Comment by natanavra** [comment]
`geolite2-redist` has some weird quirks in our production setup related to corrupted downloads/files. I've opened issues for those in that repo, but we this repo `geolite2` for over 2 years in our production, never had any issues with it in the past.
That's why I want to go back to it.

**Comment by runk** [comment]
Yeah, fair enough.

I never used google app engine, wondering if you can do following: https://cloud.google.com/appengine/docs/standard/nodejs/config/appref#environment_variables ?

**Comment by natanavra** [comment]
I'm pretty sure I tried that but the env variables are not picked by npm, it's like these are only accessible to the node process running in app engine

**Comment by runk** [comment]
I think it should be somehow possible. Consider the case when you're installing something from your private npm registry, module like `@myorg/foobar`. You'd have to have auth to npm by means of npm token that's usually setup via env var. Also I'd guess there is a way to run dockerised app, but it'd mean even more changed on your side perhaps.

**Comment by runk** [comment]
Commented on the PR. Looking good!

**Comment by runk** [comment]
Okay, now there're two alternative ways to specify the license key

https://github.com/runk/node-geolite2/blob/master/README.md#usage
