### ISSUE TITLE
Fix master branch

### ISSUE THREAD

**Issue by ALMaclaine** [runk/node-geolite2#33]
We didn't accomplish removing the dbs when we commited my previous merge, we just added more commits.

Will you enable force push to master so I can push up just the commits I had.

https://docs.github.com/en/github/administering-a-repository/enabling-force-pushes-to-a-protected-branch

I was able to do it to a remote branch here:

https://github.com/ALMaclaine/test

**Comment by ALMaclaine** [comment]
I tested the process more thoroughly just to be sure. I added more commits to ALMaclaine/test, enabled force push and was able to force push up the changes and it reset them back to just the 66. Did it twice.

**Comment by runk** [comment]
I've fixed history myself - all sorted
