### ISSUE TITLE
Update postinstall to only download if not already present

### ISSUE THREAD

**Issue by nanek** [runk/node-geolite2#38]
When using CI such as github actions, it is common to cache the node_modules folder in between runs unless there is a change to the package.json. Currently the postinstall script for geolite2 always downloads the dbs, which are quite large. In my case when on CI and restoring from cache, the dbs already exist. If we update the postinstall to only download if there are not files in the dbs folder, then we can avoid downloading these files on each run.

**Comment by runk** [comment]
A pull request with this functionality will be much appreciated ;)

**Comment by runk** [comment]
Solved via https://github.com/runk/node-geolite2/pull/41
