### ISSUE TITLE
Package does not work with pm2

### ISSUE THREAD

**Issue by Ibadichan** [runk/node-geolite2#45]
Hi! Thanks for the great library.
Our project uses `geolite2` and `pm2` to deploy the app to production.
When i deploy the app using `pm2` i see these errors on console (in development mode everything works fine):
<img width="1726" alt="Screenshot 2023-02-10 at 12 19 47" src="https://user-images.githubusercontent.com/26125121/218077961-3265cd1c-1206-4661-a464-dd74a8b3856f.png">
If i run `pm2 deploy` second time the error disappears.
Can you help me understand why this error can occur?
Thanks.

**Comment by runk** [comment]
Hey, I'm unsure if it's related to the geolite2 or pm2 itself. Maybe it's just the way you package and ship your code to production. Do you know if the file actually exists in your prod environment? Is this is the correct path to the node_modules? Did you see[ logs from geolite2](https://github.com/runk/node-geolite2/blob/master/scripts/postinstall.js#L72) where it's downloading databases and puts them in node_modules?

**Comment by Ibadichan** [comment]
Hi!
> Do you know if the file actually exists in your prod environment? 

I am using not config file but env variable `MAXMIND_LICENSE_KEY`.

> Is this is the correct path to the node_modules?

Yes, sure. After successful deploy i can navigate to this dir successfully:
<img width="1076" alt="Screenshot 2023-02-14 at 16 32 07" src="https://user-images.githubusercontent.com/26125121/218768960-1a05f84d-e149-407b-8b94-5487fec9f84e.png">

> Did you see[ logs from geolite2](https://github.com/runk/node-geolite2/blob/master/scripts/postinstall.js#L72) where it's downloading databases and puts them in node_modules?

No. I see only:
<img width="368" alt="Screenshot 2023-02-14 at 16 36 40" src="https://user-images.githubusercontent.com/26125121/218769214-95b9ae37-8c9e-4fe2-841f-36b78f21785e.png">

I use pm2 "post-deploy" hook to install deps and geolite2:
```
'post-deploy': "env-cmd yarn add geolite2 && yarn install && yarn build && ...",
```
I am using "env-cmd yarn add geolite2" after every deploy because when i run just "yarn install" i get this error:

<img width="939" alt="Screenshot 2023-02-14 at 16 40 47" src="https://user-images.githubusercontent.com/26125121/218770261-e9264661-1c6a-4a30-9451-a2289bf6b699.png">

**Comment by Ibadichan** [comment]
Seems like using config file fixes this issue.

1. Create `maxmind-licence.key` in the root of the project, add it to `.gitignore`.
2. Add this line to `package.json`:
```json
"geolite2": {
    "license-file": "./maxmind-licence.key"
  }
  ```
  3. pm2 config:
  ```
  'pre-deploy': 'ln -sf ../maxmind-licence.key maxmind-licence.key',
  'post-deploy': "yarn install && yarn build",
  ```
  4. On remote machine move `maxmind-licence.key` file to the app root:
  ```
  source current shared maxmind-licence.key
  ```
