### ISSUE TITLE
License

### ISSUE THREAD

**Issue by henriquekano** [runk/node-geolite2#5]
From what I saw from this site https://dev.maxmind.com/geoip/geoip2/geolite2/, the db files are under the Creative Commons Attribution-ShareAlike 4.0 International License, but this repository is under MIT.

Can I use this as a MIT dependency even if the CC BY-SA 4.0 states:

> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original. 

?

**Comment by knoxcard** [comment]
@runk

**Comment by runk** [comment]
This is a very good point. Will fix it!
